#ifndef LGALAKTIKA_DATA_GLOBAL_H
#define LGALAKTIKA_DATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LGALAKTIKA_DATA_LIBRARY)
#  define LGALAKTIKA_DATA_EXPORT Q_DECL_EXPORT
#else
#  define LGALAKTIKA_DATA_EXPORT Q_DECL_IMPORT
#endif

#endif // LGALAKTIKA_DATA_GLOBAL_H
